### ISSUE TITLE
FileCollisionError: Two or more packages are trying to provide the same file with different contents

### ISSUE THREAD

**Issue by seewpx** [pyproject-nix/pyproject.nix#219]
uv add live-progress

then nix build

```bash
❯ nix build
error: builder for '/nix/store/b3zn0jk61xlcp901yy75xhlrqb1nwiaz-default-venv.drv' failed with exit code 1;
       last 20 log lines:
       > Sourcing pyproject-make-venv-hook
       > Using pyprojectMakeVenv
       > Running phase: patchPhase
       > Running phase: updateAutotoolsGnuConfigScriptsPhase
       > Running phase: installPhase
       > Executing pyprojectMakeVenv
       > Traceback (most recent call last):
       >   File "/nix/store/i8mhn4rh752br27d4ydsh6gkhn46p903-make_venv.py", line 277, in <module>
       >     main()
       >     ~~~~^^
       >   File "/nix/store/i8mhn4rh752br27d4ydsh6gkhn46p903-make_venv.py", line 270, in main
       >     merged = merge_inputs([out_root, *dependencies])
       >   File "/nix/store/i8mhn4rh752br27d4ydsh6gkhn46p903-make_venv.py", line 103, in merge_inputs
       >     return {k: merge_inputs(v) for k, v in entries.items()}
       >                ~~~~~~~~~~~~^^^
       >   File "/nix/store/i8mhn4rh752br27d4ydsh6gkhn46p903-make_venv.py", line 107, in merge_inputs
       >     raise FileCollisionError(inputs)
       > FileCollisionError: Two or more packages are trying to provide the same file with different contents
       >
       >         Files: /nix/store/76fd84qmzg7n9w5yif61cmv5rr80i686-alive-progress-3.2.0/LICENSE /nix/store/r4hn0hx1bjdrshik3cw9f6h33vwk7iii-about-time-4.2.1/LICENSE
       For full logs, run 'nix log /nix/store/b3zn0jk61xlcp901yy75xhlrqb1nwiaz-default-venv.drv'.
```

please help me take a look at how this issue can be fixed?

**Comment by adisbladis** [comment]
This is caused by upstream packaging bugs in [alive-progress](https://github.com/rsalmei/alive-progress/blob/06896b9/setup.py#L60) & [about-time](https://github.com/rsalmei/about-time/blob/1026480/setup.py#L56).

I've created an issue https://github.com/pyproject-nix/pyproject.nix/issues/220 that explains the background, how to work around it, and solutions that should be implemented in pyproject.nix's venv creation.
